server {
    listen 80;
    server_name localhost;
    client_max_body_size 2M;

    location /uploads/ {
        alias /usr/share/nginx/html/uploads/;
        
        location ~ \.(php|js|sh|py|pl|cgi|exe|bat|cmd)$ {
            deny all;
        }

        default_type application/octet-stream;
        types { }
        add_header Content-Type image/jpeg;
        
        autoindex off;
        expires 30d;
    }
}